# Generated by Django 6.0.3 on 2026-09-18 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="Friendly name, e.g. 'Sarah's Samsung A55'", max_length=60)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Other')], default='android', max_length=10)),
                ('imei', models.CharField(blank=True, help_text='15-digit IMEI. Optional but recommended.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='IMEI must be exactly 15 digits.', regex='^\\d{15}$')])),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Serial number must be 4–32 characters (letters, digits, hyphens).', regex='^[A-Za-z0-9\\-]{4,32}$')])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_email', models.EmailField(blank=True, help_text='Google/Apple account email used on the device (for ID only).', max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('stolen', 'Stolen'), ('recovered', 'Recovered'), ('retired', 'Retired')], default='active', max_length=10)),
                ('consent_given', models.BooleanField(default=False, help_text='Owner has agreed that this app may collect location for this device.')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Set when the device app checks in.', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='devices_dev_owner_i_d9e88d_idx'), models.Index(fields=['imei'], name='devices_dev_imei_94ab30_idx')],
            },
        ),
    ]
