# Generated by Django 6.0.3 on 2026-09-24 09:38

import django.db.models.deletion
import parenting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age_group', models.CharField(choices=[('under_13', 'Under 13'), ('teen', 'Teen (13–17)')], default='teen', max_length=10)),
                ('parental_consent_given', models.BooleanField(default=False, help_text='Parent/guardian has confirmed they are authorised to monitor this child.')),
                ('parental_consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_paired', models.BooleanField(default=False, help_text='True once the child app has been linked with the pairing code.')),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(help_text="The child's phone, already registered as a Device.", on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to='devices.device')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=parenting.models.generate_pairing_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='parenting.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_limit_minutes', models.PositiveIntegerField(default=120, help_text='Total daily limit, Monday–Friday.')),
                ('weekend_limit_minutes', models.PositiveIntegerField(default=240, help_text='Total daily limit, Saturday–Sunday.')),
                ('bedtime_start', models.TimeField(blank=True, help_text='e.g. 21:00 — device locks at this time.', null=True)),
                ('bedtime_end', models.TimeField(blank=True, help_text='e.g. 07:00 — device unlocks at this time.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_rule', to='parenting.child')),
            ],
        ),
        migrations.CreateModel(
            name='AppUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_identifier', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage_logs', to='parenting.child')),
            ],
            options={
                'ordering': ['-day', '-total_minutes'],
                'indexes': [models.Index(fields=['child', '-day'], name='parenting_a_child_i_dcefc2_idx')],
                'unique_together': {('child', 'app_identifier', 'day')},
            },
        ),
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_identifier', models.CharField(help_text='Android package name or iOS bundle id, e.g. com.zhiliaoapp.musically', max_length=200)),
                ('app_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('limited', 'Limited'), ('blocked', 'Blocked')], default='allowed', max_length=10)),
                ('daily_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Only used when status=LIMITED.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to='parenting.child')),
            ],
            options={
                'ordering': ['app_name'],
                'unique_together': {('child', 'app_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ParentingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('app_installed', 'App installed'), ('app_blocked', 'App blocked'), ('web_blocked', 'Website blocked'), ('limit_reached', 'Screen time limit reached'), ('bedtime_start', 'Bedtime started'), ('low_battery', 'Low battery'), ('arrived_school', 'Arrived at school'), ('left_school', 'Left school'), ('paired', 'Device paired'), ('unpaired', 'Device unpaired')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parenting.child')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['child', '-occurred_at'], name='parenting_p_child_i_ab6e8b_idx'), models.Index(fields=['child', 'is_read'], name='parenting_p_child_i_546e06_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebFilterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('adult', 'Adult content'), ('gambling', 'Gambling'), ('violence', 'Violence'), ('dangerous', 'Dangerous content'), ('custom', 'Custom block')], max_length=12)),
                ('blocked_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_filter_logs', to='parenting.child')),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['child', '-blocked_at'], name='parenting_w_child_i_a45d30_idx')],
            },
        ),
    ]
