# Generated by Django 6.0.3 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture shown in the navbar.', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Swahili'), ('fr', 'Français (French)'), ('ar', 'العربية (Arabic)'), ('pt', 'Português (Portuguese)'), ('es', 'Español (Spanish)'), ('de', 'Deutsch (German)'), ('it', 'Italiano (Italian)'), ('nl', 'Nederlands (Dutch)'), ('ru', 'Русский (Russian)'), ('la', 'Latina (Latin)'), ('zh-hans', '中文（简体）(Chinese Simplified)'), ('zh-hant', '中文（繁體）(Chinese Traditional)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('hi', 'हिन्दी (Hindi)')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='location_retention_days',
            field=models.IntegerField(choices=[(7, '7 days'), (30, '30 days'), (90, '90 days'), (0, 'Keep forever')], default=90, help_text='How long location history is kept before automatic deletion.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_app_requests',
            field=models.BooleanField(default=True, help_text='When a child requests approval for an app.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_billing',
            field=models.BooleanField(default=True, help_text='Subscription renewals, receipts, payment issues.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_family',
            field=models.BooleanField(default=True, help_text='Arrivals, departures, screen-time events for your children.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email_security',
            field=models.BooleanField(default=True, help_text='SIM changes, failed unlocks, stolen-device alerts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Africa/Kampala', max_length=64),
        ),
    ]
