# Generated by Django 6.0.3 on 2026-09-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, help_text='Estimated accuracy radius in metres.', null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('network', 'Wi-Fi / Network'), ('cell', 'Cell tower'), ('last_known', 'Last known')], default='gps', max_length=16)),
                ('battery_percent', models.PositiveSmallIntegerField(blank=True, help_text='0–100, if the device reported it.', null=True)),
                ('network_operator', models.CharField(blank=True, help_text="e.g. 'MTN', 'Airtel'.", max_length=40, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='devices.device')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='locations_l_device__4700c7_idx')],
            },
        ),
    ]
