# Generated by Django 6.0.3 on 2026-09-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('power_off', 'Power off requested'), ('power_on', 'Device powered on'), ('low_battery', 'Battery low'), ('airplane_mode_on', 'Airplane mode enabled'), ('location_off', 'Location services turned off'), ('sim_removed', 'SIM card removed'), ('sim_inserted', 'SIM card inserted'), ('sim_changed', 'SIM card changed'), ('failed_unlock', 'Failed unlock attempt'), ('too_many_failed_unlocks', 'Too many failed unlock attempts'), ('marked_lost', 'Marked as lost'), ('marked_stolen', 'Marked as stolen'), ('recovered', 'Marked as recovered')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, help_text="Extra details, e.g. {'old_sim': '...', 'new_sim': '...'}", null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('battery_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(help_text='When the device says the event happened.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='locations_d_device__d12a34_idx'), models.Index(fields=['device', 'is_read'], name='locations_d_device__43983d_idx')],
            },
        ),
    ]
